// Structured source for the Test Fixture GUI Mockups deck.
// User-story and acceptance-criteria text is the spec (carried over verbatim from
// the original mockups). `shot` / `hl` point each slide at a freshly captured
// screenshot of the *current* GUI and the control to highlight on it.
// Sub-points are written as lines beginning with "  - " so the builder can indent.

const FEATURES = [
  { num: "1.1", name: "Main Window", div: "Main Window" },
  { num: "1.2", name: "Existing Test Found", div: "Existing Test Found Page" },
  { num: "1.3", name: "Test Configuration", div: "Test Configuration Page" },
  { num: "1.4", name: "Calibration", div: "Calibration Page" },
  { num: "1.5", name: "EM Test", div: "EM Test Page" },
  { num: "1.6", name: "EM Analysis", div: "EM Analysis Page" },
  { num: "1.7", name: "Shear Test", div: "Shear Test Page" },
  { num: "1.8", name: "Shear Analysis", div: "Shear Analysis Page" },
  { num: "1.9", name: "Manual Test", div: "Manual Test Page" },
  { num: "1.10", name: "Manual Analysis", div: "Manual Analysis Page" },
  { num: "1.11", name: "Cyclical Test", div: "Cyclical Test Page" },
];

const S = [
  // ===================================================== 1.1 MAIN WINDOW
  { id: "1.1.1", f: "1.1", title: "Main Window", shot: "main",
    us: "As a test fixture operator, I want the Main Window to clearly display the basic setup fields so that I can prepare and run a sensor test from one central interface.",
    ac: [
      'When a user initially opens the application, they should be greeted with the main window that includes the title: "Zaber Stage Testing Setup"',
      "Note: Does not need to create buttons/widgets for the settings; just creates titles for each section on the page",
    ] },
  { id: "1.1.2", f: "1.1", title: "Save Folder Field", shot: "main", hl: "saveFolder",
    us: "As a test fixture operator, I want to choose where test outputs are saved so that plots, Excel files, and analysis results are stored in the correct folder.",
    ac: [
      "The user can type a save folder path",
      "The user can browse and select a save folder",
      "If a save folder is selected, test outputs are saved there",
      "If no save folder is selected, the system uses the default/root directory",
      "If the save folder does not exist, the system creates the needed folders",
      'Info note below the field: "Missing folders will be automatically created before a run"',
    ] },
  { id: "1.1.3", f: "1.1", title: "Sensor ID Field", shot: "main", hl: "sensorId",
    us: "As a test fixture user, I want to enter the Sensor ID through one connected segmented field so that the ID format is easier to follow and less likely to be mistyped.",
    ac: [
      "Sensor ID input is one connected row with segments: YY, MM, DD, Batch, Sensor, Location",
      'Batch visually includes fixed prefix "B"; user enters only the number. Same for Sensor ("S")',
      "Generated Sensor ID follows: YYMMDDB##S##X",
      "  - Requirements: Year, Month, Day each 2 digits; Batch and Sensor each 2 numeric digits; Location must be A, B, or AB",
      "  - Example valid IDs: 250506B01S01A, 250506B01S01B, 250506B01S01AB",
      "Completed Sensor ID is used in test completion messages, saved outputs, and analysis",
    ] },
  { id: "1.1.4", f: "1.1", title: "Custom Sensor ID Checkbox", shot: "main_custom", hl: "customField",
    us: "As a test fixture user, I want the option to use a custom Sensor ID so that I can test experimental or nonstandard sensors.",
    ac: [
      'The Main Window includes a checkbox labeled "Use Custom Sensor ID"',
      "When unchecked, the segmented Sensor ID field is active",
      "When checked, the segmented Sensor ID field is disabled and a custom free-text Sensor ID input becomes active",
      "The custom Sensor ID is used for testing, saving, and analysis",
    ] },
  { id: "1.1.5", f: "1.1", title: "Sensor ID Validation / Preview", shot: "main", hl: "sensorPreview",
    us: "As a test fixture user, I want the GUI to validate Sensor ID formatting so that mistyped sensor IDs do not cause data to be saved under the wrong sensor.",
    ac: [
      "If all segments are complete, the GUI displays the full generated Sensor ID",
      'If any segment is missing, the GUI displays: "Sensor ID: complete all segments"',
      "The Sensor ID preview updates whenever any segment changes",
    ] },
  { id: "1.1.6", f: "1.1", title: "Sensor Type Dropdown", shot: "main", hl: "sensorType",
    us: "As a test fixture user, I want to select the sensor type so that the system can interpret the sensor data using the correct firmware/channel configuration.",
    ac: [
      "The user can select a Sensor Type from a dropdown; options: Standard, Inverted",
      "  - Standard orders the channels [1, 2, 3, 4, 5, 6, 7, 8]",
      "  - Inverted orders the channels [1, 2, 3, 4, 8, 7, 6, 5]",
      "Standard is selected by default",
      "The selected Sensor Type is passed into the analysis workflow",
      "Info note below the field explains the sensor type per firmware version / channel configuration",
    ] },
  { id: "1.1.7", f: "1.1", title: "Verify Settings Button", shot: "main", hl: "verify",
    us: "As a test fixture user, I want to click Verify Settings so that I can confirm the setup parameters before the test begins.",
    ac: [
      "Clicking Verify Settings proceeds to the Test Configuration page",
      'If Save Folder is blank: block, warn "Fill in Save Folder before continuing"',
      'If Custom Sensor ID enabled and blank: block, warn "Enter a custom sensor ID"',
      'If Sensor Type is blank: block, warn "Fill in Sensor Type"',
      'If Custom Sensor ID disabled and any Sensor ID segment is incomplete: block, warn "Complete all Sensor ID segments before continuing"',
      "If any Sensor ID segment is invalid: block with an appropriate validation message",
      "If Sensor ID already has pre-existing tests from the same day, the Existing Test Found dialog opens (Feature 1.2)",
      "If all required fields are valid, the Test Configuration section becomes visible",
    ] },
  { id: "1.1.8", f: "1.1", title: "Basic Settings Reverification Behavior", shot: "main_reverify", hl: "message",
    us: "As a test fixture user, I want the Test Configuration section to disappear when Basic Settings are changed so that tests cannot begin using outdated or unverified setup information.",
    ac: [
      "If the user edits any Basic Settings field after verification, the Test Configuration section disappears",
      'The GUI displays: "Basic settings changed. Please click Verify again"',
      "The user must click Verify again before continuing to Test Configuration",
      "Previously entered Test Configuration settings are not used until Basic Settings are reverified",
    ] },
  { id: "1.1.9", f: "1.1", title: "Info Icons", shot: "help_icons", hl: "help",
    us: "As a test fixture user, I want informational help icons throughout the window so that I can quickly understand fields, workflows, and testing terminology without needing external documentation.",
    ac: [
      "Informational help icons appear beside important labels and controls throughout the GUI",
      "Hovering over a help icon displays an info tooltip",
      "Tooltips automatically disappear when the user moves away from the icon",
      "Tooltips use concise explanations and do not block surrounding UI interaction unnecessarily",
    ] },

  // ===================================================== 1.2 EXISTING TEST FOUND
  { id: "1.2.1", f: "1.2", title: "Existing Test Found Popup", shot: "existing_test",
    us: "As a test fixture user, I want the software to warn me when a matching test folder already exists for a specified sensor so that I can decide how to continue without accidentally overwriting previous data.",
    ac: [
      'If an existing test-session folder already exists, the GUI displays an "Existing Test Found" popup window',
      "The popup displays the full existing test path (e.g., /Users/.../Test Data/12345/05 21 26_325mm2_EM)",
      'The popup displays: "A test folder already exists for this Sensor ID and test configuration. Choose how you want to continue."',
    ] },
  { id: "1.2.2", f: "1.2", title: "Redo a Specific Run Button", shot: "existing_test", hl: "redo",
    us: "As a test fixture user, I want to redo a specific run from an existing test so that I can repeat failed or invalid runs without restarting the entire test session.",
    ac: [
      'The Existing Test Found popup includes a button: "Redo a Specific Run"',
      "Redo a Specific Run functionality only applies to EM Testing workflows (not supported for Shear, Manual, or Cyclical testing).",
      '  - If the existing test was created from a Shear, Manual, or Cyclical test, the "Redo a Specific Run" button is disabled.',
      "Clicking the button opens the Test Configuration Window in Redo Run mode",
      "In Redo Run mode, EM Test is automatically selected and cannot be modified",
      "In Redo Run mode, Number of Runs is automatically set to 1 and cannot be modified",
      'The "Run to Redo" field becomes enabled; user specifies which run to repeat',
      "The system only repeats the selected run instead of restarting the entire test sequence",
    ] },
  { id: "1.2.3", f: "1.2", title: "Overwrite Existing Test Button", shot: "existing_test",
    us: "As a test fixture user, I want the option to overwrite an existing test folder so that I can intentionally replace previous test data when needed.",
    ac: [
      'The Existing Test Found popup includes a button: "Overwrite Existing Test"',
      "Clicking the button opens the Test Configuration Window and allows the workflow to overwrite the existing test-session folder and outputs",
      "The system displays a confirmation warning before overwriting existing data",
    ] },
  { id: "1.2.4", f: "1.2", title: "Create New Versioned Test Folder Button", shot: "existing_test", hl: "versioned",
    us: "As a test fixture user, I want to create a new versioned test folder so that I can preserve previous test data while starting a new test session.",
    ac: [
      'The Existing Test Found popup includes a button: "Create New Versioned Test Folder"',
      "Clicking the button opens the Test Configuration Window and creates a new versioned test-session folder instead of overwriting",
      "The new versioned folder is used for all new FUT, CAP, and analysis outputs",
    ] },
  { id: "1.2.5", f: "1.2", title: "Cancel Button", shot: "existing_test",
    us: "As a test fixture user, I want to cancel the Existing Test Found workflow so that I can safely stop the current action without modifying any files or starting a test.",
    ac: [
      'The Existing Test Found popup includes a button: "Cancel"',
      "Clicking the button closes the popup window",
      "No test begins",
      "No files or folders are modified",
    ] },

  // ===================================================== 1.3 TEST CONFIGURATION
  { id: "1.3.1", f: "1.3", title: "Test Configuration Window", shot: "test_config",
    us: "As a test fixture user, I want the Test Configuration window to clearly display the test setup fields so that I can prepare and run a sensor test.",
    ac: [
      'Clicking the "Verify Settings" button opens the Test Configuration window with the title: "Test Configuration Window"',
    ] },
  { id: "1.3.2", f: "1.3", title: "Test Type Dropdown", shot: "test_config", hl: "testType",
    us: "As a test fixture user, I want to select the Test Type so that the correct testing workflow and analysis pipeline are used.",
    ac: [
      "User can select Test Type from a dropdown; options: EM Test, Shear Test, Manual Test, Cyclical Test",
      "The selected Test Type is passed into the testing and analysis workflow",
      "EM Test: enables Number of Runs, Zaber COM Port, and Pause Between Runs",
      "Shear Test: disables Number of Runs, Zaber COM Port, and Pause Between Runs",
      "Manual Test: disables Number of Runs and Run to Redo; Zaber COM Port stays enabled",
      "Cyclical Test: disables Number of Runs and Run to Redo; Zaber COM Port stays enabled; cyclical waveform controls become visible",
    ] },
  { id: "1.3.3", f: "1.3", title: "Number of Runs Integer Field", shot: "test_config", hl: "runs",
    us: "As a test fixture user, I want to choose the number of runs so that repeated testing can be automated.",
    ac: [
      "The user can enter the number of runs",
      "Default number of runs = 3",
      "The field only accepts positive integers",
      "The field only enables for the EM Test",
    ] },
  { id: "1.3.4", f: "1.3", title: "Zaber COM Port Dropdown", shot: "test_config", hl: "comport",
    us: "As a test fixture user, I want to define the Zaber COM Port so that the software can connect to the correct actuator.",
    ac: [
      "The user can enter or select a Zaber COM Port",
      "Default value = COM3",
      "The selected COM Port is used during hardware initialization",
      "The field only enables for the EM Test, Manual Test, and Cyclical Test",
    ] },
  { id: "1.3.5", f: "1.3", title: "Surface Area Integer Field", shot: "test_config", hl: "surfaceArea",
    us: "As a test fixture user, I want to enter the Ecoflex block surface area so that pressure calculations are accurate.",
    ac: [
      "The user can enter a Surface Area value",
      "Default units are displayed as mm²",
      "The field only accepts positive numeric values",
      "The Surface Area value is passed into the analysis workflow",
    ] },
  { id: "1.3.6", f: "1.3", title: "Run to Redo Integer Field", shot: "test_config", hl: "runToRedo",
    us: "As a test fixture user, I want to enter the specific run number I want to redo so that the system repeats only that selected run. Available only when I choose to redo a run from an existing test.",
    ac: [
      "The Run to Redo field is disabled by default",
      'It becomes enabled only when the user selects "Redo a Specific Run" from the Existing Test Found popup',
      "In Redo Mode, Test Type is automatically set to EM Test and cannot be modified",
      "In Redo Mode, Number of Runs is automatically set to 1 and cannot be modified",
      "The user can enter a positive integer for Run to Redo",
      "When the test begins, the system repeats only the selected run",
    ] },
  { id: "1.3.7", f: "1.3", title: "Begin Test Button", shot: "test_config", hl: "begin",
    us: "As a test fixture user, I want to click Begin Test so that the specified test can begin using the selected configuration settings.",
    ac: [
      "Clicking Begin Test starts the testing workflow and opens the appropriate Testing Window (EM/Shear/Manual/Cyclical)",
      "The system attempts hardware initialization before actuator movement begins",
      'If Test Type is blank: block, warn "Fill in Test Type before continuing"',
      "EM + Number of Runs blank or invalid: block with matching validation message",
      'EM / Manual / Cyclical + Zaber COM Port blank: block, warn "Fill in Zaber COM Port before continuing"',
      'Surface Area blank: block, warn "Fill in Surface Area before continuing"',
      'Surface Area invalid: block, warn "Surface Area must be a positive number"',
      "Redo Mode + Run to Redo blank/invalid: block with matching validation message",
      "If Redo Mode is active, the system begins only the selected run instead of the full test sequence",
    ] },
  { id: "1.3.8", f: "1.3", title: "Open Calibration Button", shot: "test_config", hl: "openCalib",
    us: "As a test fixture user, I want to open the Calibration Window so that I can perform the Fuji Film calibration before testing.",
    ac: ["The user can click Open Calibration to open the Calibration Window popup"] },
  { id: "1.3.9", f: "1.3", title: "Info Icons", shot: "test_config",
    us: "As a test fixture user, I want informational help icons throughout the window so that I can quickly understand fields, workflows, and testing terminology without needing external documentation.",
    ac: [
      "Help icons appear beside important labels and controls",
      "Hovering displays a concise info tooltip that disappears on mouse-out",
      "Tooltips do not block surrounding UI interaction unnecessarily",
    ] },

  // ===================================================== 1.4 CALIBRATION
  { id: "1.4.1", f: "1.4", title: "Calibration Configuration Window", shot: "calibration",
    us: "As a test fixture user, I want a separate Calibration window so that I can safely perform the Fuji Film Test before beginning the specified test.",
    ac: ['Clicking the "Open Calibration" button opens a popup window titled: "Calibration for Fuji Film Test"'] },
  { id: "1.4.2", f: "1.4", title: "Current Status Display", shot: "calibration",
    us: "As a test fixture user, I want to see the current actuator position during calibration so that I can safely adjust the actuator location.",
    ac: [
      "Current Status displays Position only, in mm",
      "Position updates when the user clicks Move Up, Move Down, or Home",
    ] },
  { id: "1.4.3", f: "1.4", title: "Manual Increment Control", shot: "calibration",
    us: "As a test fixture user, I want to move the actuator in small increments so that I can fine-tune the actuator position safely.",
    ac: [
      "The user can enter an Increment Distance (mm)",
      "The user can click Move Up or Move Down; the actuator moves by the entered increment",
      "Move Up/Down update position step-by-step, with no elapsed-time output",
      "Increment Distance must remain within a specified maximum allowed range",
      'If blank: block, warn "Fill in Increment Distance before continuing"',
      'If exceeds range: block, warn "Increment Distance exceeds the maximum allowed range"',
      'If non-numeric: block, warn "Increment Distance must be a valid number"',
    ] },
  { id: "1.4.4", f: "1.4", title: "Reset to Home Button", shot: "calibration",
    us: "As a test fixture user, I want a Home button so that I can safely return the actuator to its original position.",
    ac: [
      "Clicking Home returns the actuator to the home/original position",
      "The GUI displays that the actuator has reset successfully",
    ] },
  { id: "1.4.5", f: "1.4", title: "Calibration Test Button", shot: "calibration",
    us: "As a test fixture user, I want to run a Calibration Test so that I can calibrate the load cell and actuator setup.",
    ac: [
      'The user can click "Begin Calibration Test"',
      "The actuator moves downward until the target force is reached",
      "Target Force = 20 N",
      "Motion stops when the target force is reached",
    ] },
  { id: "1.4.6", f: "1.4", title: "Calibration Test Output Box", shot: "calibration",
    us: "As a test fixture user, I want Calibration Test force readings displayed in a table-like format so that I can clearly track force over time during calibration.",
    ac: [
      'When the test starts, the output box displays: "Calibration Test started"',
      "Output box includes column headers: Time (s) | Force (N)",
      "While running, force values are displayed in the output box with time values",
      'On reaching target force, the GUI displays under the button: "Calibration Test Completed Successfully"',
      "If the test stops due to a force spike or error, an error status is displayed instead of a success message",
    ] },
  { id: "1.4.7", f: "1.4", title: "Exit Button", shot: "calibration",
    us: "As a test fixture user, I want an Exit button on the Calibration popup window so that I can close the Calibration Window.",
    ac: [
      "The Calibration popup window includes an Exit button",
      "Clicking the Exit button closes only the Calibration popup window",
      "The Exit button is disabled while the Calibration Test is actively running",
      "Once the Calibration Test is complete or stopped, the Exit button becomes enabled again",
    ] },

  // ===================================================== 1.5 EM TEST
  { id: "1.5.1", f: "1.5", title: "EM Testing Window", shot: "em_test",
    us: "As a test fixture user, I want the EM test to open in a dedicated EM Testing Window so that I can monitor and control the active EM test.",
    ac: ['Clicking Begin Test with Test Type = EM Test opens a new window titled: "EM Testing Window"'] },
  { id: "1.5.2", f: "1.5", title: "Current EM Test Output Box", shot: "em_test", hl: "status",
    us: "As a test fixture user, I want to view the current EM test status so that I can monitor the actuator and testing workflow in real time.",
    ac: [
      "The EM Testing Window includes a Current EM Test Status display area",
      "The output box includes column headers: Run Number | Time (s) | Force (N)",
      "Force readings are displayed in chronological order (e.g., Run 1 | 4.802 s | 4.941 N)",
      "Status display updates with key states: IDLE, READY, CONNECTING, RUNNING, PAUSED_RESET_REQUIRED, BETWEEN_RUNS_PAUSED, COMPLETED, ERROR",
    ] },
  { id: "1.5.3", f: "1.5", title: "Start Button", shot: "em_test", hl: "start",
    us: "As a test fixture user, I want to click START so that the EM test begins using the selected configuration settings.",
    ac: [
      "Clicking the Start Button begins the EM testing workflow",
      "The system attempts hardware initialization before movement begins",
      "The actuator does not move unless initialization succeeds",
      "Once testing begins, START becomes disabled",
    ] },
  { id: "1.5.4", f: "1.5", title: "Pause Button", shot: "em_test", hl: "pause",
    us: "As a test fixture user, I want to pause the current EM test safely so that actuator motion stops and the current run can be repeated.",
    ac: [
      "Clicking the Pause Button immediately stops actuator motion",
      "The actuator returns to the home/original position",
      "The current run is marked incomplete",
      "The current run number does not increment",
      "The current run must be repeated before continuing",
    ] },
  { id: "1.5.5", f: "1.5", title: "Live Force vs Time Graph", shot: "em_test", hl: "graph",
    us: "As a test fixture user, I want to view a live Force vs Time graph so that I can visually monitor force trends during the EM test.",
    ac: [
      "The EM Testing Window includes a Live Force vs Time graph",
      "The graph updates in real time while the EM test is running",
      "The graph displays force in N over time in seconds",
      "The graph resets appropriately between runs",
    ] },
  { id: "1.5.6", f: "1.5", title: "Perform Analysis Button", shot: "em_test", hl: "analysis",
    us: "As a test fixture user, I want to click a Perform Analysis button so that the software can process the completed test data and generate summary statistics and plots.",
    ac: [
      "The testing window includes a Perform Analysis button",
      "Perform Analysis is disabled until the EM test has completed successfully",
      "Clicking Perform Analysis should show a loading/progress state before opening the EM Analysis Page",
    ] },

  // ===================================================== 1.6 EM ANALYSIS
  { id: "1.6.1", f: "1.6", title: "EM Analysis Window", shot: "em_an_raw", hl: "tabs",
    us: "As a test fixture user, I want analysis results to open in a dedicated results window so that I can review processed EM test results after testing completes.",
    ac: [
      'After analysis completes, a new window opens titled: "EM Analysis Data and Plots"',
      "The window displays summary statistics and plots generated from the selected test data",
      "Users can click between tabs to quickly navigate different EM analysis outputs",
    ] },
  { id: "1.6.2", f: "1.6", title: "Raw Signals Tab", shot: "em_an_raw",
    us: "As a test fixture user, I want to view raw EM test signals so that I can inspect channel behavior before processed analysis is applied.",
    ac: [
      "The Raw Signals tab displays raw channel plots for the selected run",
      "The tab displays all EM channels simultaneously",
      "Users can switch between runs",
    ] },
  { id: "1.6.3", f: "1.6", title: "Pressure Sensitivity Curves Tab", shot: "em_an_ps",
    us: "As a test fixture user, I want to view pressure sensitivity curves so that I can evaluate how capacitance changes relative to pressure.",
    ac: [
      "The Pressure Sensitivity Curves tab displays processed pressure sensitivity plots for all channels",
      "Each channel plot includes the calculated pressure sensitivity value",
      "Inflection points are visually highlighted on the plots",
    ] },
  { id: "1.6.4", f: "1.6", title: "All Channels / Runs Comparison Tab", shot: "em_an_all",
    us: "As a test fixture user, I want to compare all runs and channels simultaneously so that I can evaluate consistency and repeatability across the sensor.",
    ac: [
      "The All CH/Runs tab includes comparison views for: By Channel (all runs), By Run (all channels)",
      "Each plot overlays multiple runs for direct comparison",
    ] },
  { id: "1.6.5", f: "1.6", title: "Summary Statistics Tab", shot: "em_an_summary",
    us: "As a test fixture user, I want to view summary statistics for all EM channels so that I can evaluate sensor quality quantitatively.",
    ac: [
      "The Summary Statistics tab displays a table of calculated metrics for all channels",
      "Metrics include Mean, Std, COV, Min, and Max for: PS at Inflection, Max kPa, Mean Max CAP",
      "Every displayed average metric also includes standard deviation",
      "Every displayed maximum metric also includes minimum values",
    ] },
  { id: "1.6.6", f: "1.6", title: "Report Output Tab", shot: "em_an_report",
    us: "As a test fixture user, I want a report-style output tab so that I can easily copy, export, and review finalized EM testing results.",
    ac: [
      "The Report Output tab displays a formatted summary report table",
      "Includes: Lot Number / Sensor ID, Electromechanical Standards Status, Software Version, Date Tested, Fabrication Type, Eco Block ID, Run Number Tested, Run Number Counted",
      "Shorted Channel Status: the analysis pipeline automatically checks for potential channel shorting behavior",
      'The tab includes a "Copy Values" button',
      'Clicking "Copy Values" copies only the data row (not the headers) to quickly transfer results into reports',
    ] },

  // ===================================================== 1.7 SHEAR TEST
  { id: "1.7.1", f: "1.7", title: "Shear Testing Window", shot: "shear_test",
    us: "As a test fixture user, I want the Shear Test to open in a dedicated Shear Testing Window so that I can monitor and control the active Shear test.",
    ac: ['Clicking Begin Test with Test Type = Shear Test opens a new window titled: "Shear Testing Window"'] },
  { id: "1.7.2", f: "1.7", title: "Live Shear Graph Display", shot: "shear_test", hl: "graph",
    us: "As a test fixture user, I want to view the live Shear graph so that I can monitor force behavior in real time during testing.",
    ac: [
      'Graph X-axis is labeled: "Time Elapsed (seconds)"',
      'Graph Y-axis is labeled: "Force (N)"',
      "The graph updates in real time during the Shear test",
      "The graph displays live force data from the load cell",
      "Hovering over the graph displays the current time and force values (e.g., Time: 0.000 s, Force: 0.000 N)",
    ] },
  { id: "1.7.3", f: "1.7", title: "Graph Display Controls", shot: "shear_test", hl: "controls",
    us: "As a test fixture user, I want to control the graph display settings so that I can customize how the Shear test data is visualized.",
    ac: [
      'The user can edit the "Last Seconds to Display" field',
      'The user can edit the "Y-Axis Min" field',
      'The user can edit the "Y-Axis Limit" field',
      'The user can toggle the "Show Markers" checkbox to display visible graph markers',
      'The user can toggle the "Cumulative Time" checkbox',
      "Changing these settings updates the graph display",
    ] },
  { id: "1.7.4", f: "1.7", title: "Start Button", shot: "shear_test", hl: "start",
    us: "As a test fixture user, I want to click START so that the live Shear test begins.",
    ac: [
      "Clicking START begins the Shear testing workflow",
      "The graph begins updating in real time",
      "START becomes disabled while the test is running, and after PAUSE when the actuator is moving",
      "Clicking Start after a paused/incomplete run begins a new active run dataset",
    ] },
  { id: "1.7.5", f: "1.7", title: "Stop Button", shot: "shear_test", hl: "stop",
    us: "As a test fixture user, I want to stop the Shear test so that I can stop graph updates and actuator movement safely.",
    ac: [
      "Clicking STOP stops the active Shear workflow",
      "START becomes enabled after Stop is clicked.",
      "PERFORM ANALYSIS becomes enabled only after START has been clicked, valid data has been collected, and STOP has been clicked.",
      "If the user clicks Start again after stopping, the previous stopped/incomplete graph data is replaced by the newest run dataset.",
      "Perform Analysis uses the newest valid stopped run dataset.",
    ] },
  { id: "1.7.6", f: "1.7", title: "Perform Analysis Button", shot: "shear_test", hl: "analysis",
    us: "As a test fixture user, I want to click Perform Analysis after test data has been collected so that the software can process the latest available test data and generate summary statistics and plots.",
    ac: [
      "The Testing Window includes a Perform Analysis button",
      "Perform Analysis is disabled before testing starts, then becomes enabled after Start has been clicked, valid test data has been collected, and Stop has been clicked.",
      "If user pauses the test and restarts the run, the previously paused/incomplete graph data is not saved as the active dataset",
      "When clicked, analysis is generated using the newest/latest valid run data",
      "Clicking Perform Analysis shows a loading state before opening the Shear Analysis Page.",
    ] },
  { id: "1.7.7", f: "1.7", title: "Info Icons", shot: "shear_test",
    us: "As a test fixture user, I want informational help icons throughout the window so that I can quickly understand fields, workflows, and testing terminology without needing external documentation.",
    ac: [
      "Help icons appear beside important labels and controls",
      "Hovering displays a concise info tooltip that disappears on mouse-out",
      "Tooltips do not block surrounding UI interaction unnecessarily",
    ] },

  // ===================================================== 1.8 SHEAR ANALYSIS
  { id: "1.8.1", f: "1.8", title: "Shear Analysis Window", shot: "sh_an_plot", hl: "tabs",
    us: "As a test fixture user, I want analysis results to open in a dedicated results window with tabs so that I can review processed Shear Test results in an organized way.",
    ac: [
      'After analysis completes, a new window opens titled: "Shear Analysis Data and Plots"',
      "Shear Analysis tabs may include: Plots, Failure Checks, Report Output",
      "Users can click between tabs to view different plots and metrics",
    ] },
  { id: "1.8.2", f: "1.8", title: "Plot Tab", shot: "sh_an_plot",
    us: "As a test fixture user, after clicking Perform Analysis on a shear test I want to view a plot summary of the test.",
    ac: [
      "The tab displays a graph for each capacitance channel and one final graph for outputted force over time",
      "The X axis for each graph is Time (seconds)",
      "The Y axis for each capacitance channel includes both Capacitance (pF) and delta Capacitance (pF)",
      "The final graph Y axis is Force (Newtons)",
    ] },
  { id: "1.8.3", f: "1.8", title: "Detection Table Tab", shot: "sh_an_detection",
    us: "As a test fixture user, I want to know which capacitance channels had negative values and which had a large delta after performing a shear test.",
    ac: [
      "The tab displays a grid where each column is a capacitance channel",
      "One row shows negative values (pF) if detected, or None",
      "One row shows delta values (pF) if a high delta was detected, or None",
      "A high delta is defined as greater than 10 pF",
    ] },
  { id: "1.8.4", f: "1.8", title: "Report Outputs Tab", shot: "sh_an_report",
    us: "As a test fixture user, I want to easily copy information from the Shear analysis summary so I can document it later.",
    ac: [
      "The tab includes: Sensor ID, Test Result (Pass/Fail), Shorted Channels Ch 1-N, Test Date DD/MM/YEAR, Test Taker Initials, Test Version",
      'User can copy values via the "Copy Values" button',
      "Copied values should be pastable into Excel format",
    ] },

  // ===================================================== 1.9 MANUAL TEST
  { id: "1.9.1", f: "1.9", title: "Manual Testing Window", shot: "manual_test",
    us: "As a test fixture user, I want the Manual Test to open in a dedicated Manual Testing Window so that I can manually control the Zaber stage and perform custom tests.",
    ac: [
      'Clicking Begin Test with Test Type = Manual Test opens a new window titled: "Manual Testing Window"',
      "The window includes manual control settings, actuator movement controls, live graphs, graph display controls, Pause, and Perform Analysis",
    ] },
  { id: "1.9.2", f: "1.9", title: "Control By Distance", shot: "manual_test", hl: "primary",
    us: "As a test fixture user, I want to manually control actuator movement by distance so that I can perform precise step-by-step actuator positioning and exploratory testing.",
    ac: [
      'When "Control By = Distance" is selected, the window displays: Increment Distance, Actuator Speed, Move Up, Move Down, Home',
      "User enters Increment Distance (mm) and Actuator Speed (mm/s)",
      "Move Up moves the actuator upward using the specified Increment Distance and Actuator Speed",
      "Move Down moves the actuator downward using the specified Increment Distance and Actuator Speed",
      "Home returns the actuator to the home/original position",
      "Current position and live graphs update after movement",
      "Movement controls are temporarily disabled while the actuator is moving; re-enabled when motion completes",
    ] },
  { id: "1.9.3", f: "1.9", title: "Control By Force", shot: "manual_test_force", hl: "primary",
    us: "As a test fixture user, I want to manually control actuator movement by force so that I can perform force-based compression testing and exploratory sensor characterization.",
    ac: [
      'When "Control By = Force" is selected, the window displays: Target Force, Actuator Speed, Release, Start Compression, Home',
      "User enters Target Force (N) and Actuator Speed (mm/s)",
      "Start Compression begins actuator compression toward the selected Target Force",
      "Release releases the applied compression or moves the actuator upward",
      "Home returns the actuator to the home/original position",
      "Live graphs update during compression and release behavior",
      "Movement controls are temporarily disabled while the actuator is moving or compressing",
    ] },
  { id: "1.9.4", f: "1.9", title: "Drag Position Control", shot: "manual_test", hl: "drag",
    us: "As a test fixture user, I want to stage actuator movement using a slider so that I can preview the desired position before physically moving the actuator.",
    ac: [
      "The window includes a Drag Position Control slider",
      "Dragging the slider only stages a move and does not move the actuator",
      "The readout displays the selected position and travel from baseline",
      "Confirm Drag Move remains disabled until the slider changes",
      "The actuator only moves after the user clicks Confirm Drag Move",
      "Movement controls and Confirm Drag Move are disabled during active movement",
      "Current position and live graphs update after movement completes",
    ] },
  { id: "1.9.5", f: "1.9", title: "Manual Test Live Graphs", shot: "manual_test", hl: "graphs",
    us: "As a test fixture user, I want live graphs during manual testing so that I can monitor sensor behavior while manually moving the actuator.",
    ac: [
      "The window displays three live graphs: Capacitance vs Force, Force vs Time, Capacitance vs Time",
      "Graphs update when movement or compression occurs",
    ] },
  { id: "1.9.6", f: "1.9", title: "Graph Display Controls", shot: "manual_test", hl: "controls",
    us: "As a test fixture user, I want graph display controls so that I can customize how live data is visualized.",
    ac: [
      "The user can edit Last Seconds to Display",
      "The user can edit Y-Axis Min",
      "The user can edit Y-Axis Limit",
      "The user can toggle Show Markers",
      "The user can toggle Cumulative Time",
    ] },
  { id: "1.9.7", f: "1.9", title: "Pause Button", shot: "manual_test", hl: "pause",
    us: "As a test fixture user, I want to pause Manual Testing so that I can stop active movement or graph updates safely.",
    ac: [
      "Clicking Pause stops active actuator movement",
      "Graph updates pause while the workflow is paused",
      "Movement controls remain locked until the system is safe/ready again",
    ] },
  { id: "1.9.8", f: "1.9", title: "Perform Analysis Button", shot: "manual_test", hl: "analysis",
    us: "As a test fixture user, I want to perform analysis on manual test data so that I can review results from the current preview/manual dataset.",
    ac: [
      "Perform Analysis becomes available after manual test data exists",
      "Clicking Perform Analysis generates manual analysis from the current preview data",
      "Shows a loading state before opening the Manual Analysis Page",
    ] },
  { id: "1.9.9", f: "1.9", title: "Info Icons", shot: "manual_test",
    us: "As a test fixture user, I want informational help icons throughout the window so that I can quickly understand fields, workflows, and testing terminology without needing external documentation.",
    ac: [
      "Help icons appear beside important labels and controls",
      "Hovering displays a concise info tooltip that disappears on mouse-out",
      "Tooltips do not block surrounding UI interaction unnecessarily",
    ] },

  // ===================================================== 1.10 MANUAL ANALYSIS
  { id: "1.10.1", f: "1.10", title: "Manual Analysis Window", shot: "man_an_forcetime", hl: "tabs",
    us: "As a test fixture user, I want Manual Test results to open in a dedicated analysis window so that I can review the data collected during manual actuator movement.",
    ac: [
      'Clicking Perform Analysis from the Manual Testing Window opens a new window titled: "Manual Analysis Data and Plots"',
      "The window displays plots generated from the current manual test data",
      "The window includes tabs for different manual analysis plots",
    ] },
  { id: "1.10.2", f: "1.10", title: "Manual Analysis Plot Tabs", shot: "man_an_forcetime", hl: "tabs",
    us: "As a test fixture user, I want Manual Analysis plots organized into tabs so that I can switch between different sensor relationships easily.",
    ac: [
      "Tabs include: Capacitance vs Force, Force vs Time, Capacitance vs Time",
      "Clicking each tab updates the displayed plot",
      "Plots are generated from the current manual test data",
      "Data points are shown with markers and connected by a line",
    ] },

  // ===================================================== 1.11 CYCLICAL TEST
  { id: "1.11.1", f: "1.11", title: "Cyclical Testing Window", shot: "cyclical_test",
    us: "As a test fixture user, I want the Cyclical Test to open in a dedicated Cyclical Testing Window so that I can monitor and control a cyclical test.",
    ac: ['Clicking Begin Test with Test Type = Cyclical Test opens a new window titled: "Cyclical Testing Window"'] },
  { id: "1.11.2", f: "1.11", title: "Waveform Type Dropdown", shot: "cyclical_test", hl: "waveform",
    us: "As a test fixture user, I want to perform cyclical tests with different waveform outputs.",
    ac: [
      'User can click a "Waveform Type" dropdown menu',
      "Options include: Sine, Square",
    ] },
  { id: "1.11.3", f: "1.11", title: "Lower Force Bound Integer Field", shot: "cyclical_test", hl: "lower",
    us: "As a test fixture user, I want to control the lower bound of the waveform during a cyclical test.",
    ac: [
      'User enters a positive integer into the "Lower Force Bound (N)" field',
      "The integer must be strictly greater than 0",
      "The integer must be strictly lower than the Upper Force Bound (N) value",
      "Otherwise, an error message displays informing the user the lower bound is larger than the upper bound",
      "Default lower bound is 1 Newton",
    ] },
  { id: "1.11.4", f: "1.11", title: "Upper Force Bound Integer Field", shot: "cyclical_test", hl: "upper",
    us: "As a test fixture user, I want to control the upper bound of the waveform during a cyclical test.",
    ac: [
      'User enters a positive integer into the "Upper Force Bound (N)" field',
      "The integer must be lower than or equal to 32 Newtons",
      "The integer must be strictly higher than the Lower Force Bound (N) value",
      "Otherwise, an error message displays informing the user the upper bound is lower than the lower bound",
      "Default upper bound is 20 Newtons",
    ] },
  { id: "1.11.5", f: "1.11", title: "Frequency Integer Field", shot: "cyclical_test", hl: "frequency",
    us: "As a test fixture user, I want to control how many cycles occur per second by manipulating the frequency of the cyclical waveform.",
    ac: [
      'User enters a positive integer into the "Frequency (Hz)" field',
      "The integer represents the number of wave cycles that occur per second",
      "Default frequency is 1 Hertz",
    ] },
  { id: "1.11.6", f: "1.11", title: "Number of Cycles Integer Field", shot: "cyclical_test", hl: "cycles",
    us: "As a test fixture user, I want to control the number of cycles that should be completed before the test ends.",
    ac: [
      'User enters a positive integer into the "Number of Cycles" field',
      "A message below the field displays the test duration computed from Frequency and Number of Cycles",
      "Default is 28,800 cycles (8 hours at 1 Hz)",
    ] },
  { id: "1.11.7", f: "1.11", title: "Start Button", shot: "cyclical_test", hl: "start",
    us: "As a test fixture user, I want to start a cyclical test.",
    ac: [
      'User clicks a "Start" button to begin the Cyclical test',
      "All input fields must be filled in with valid values for the test to begin",
      "Once Start is clicked, all input fields are disabled",
    ] },
  { id: "1.11.8", f: "1.11", title: "Stop Button", shot: "cyclical_test", hl: "stop",
    us: "As a test fixture user, I want to pause a cyclical test while it is running.",
    ac: [
      'User clicks a "Stop" button to pause the Cyclical test while it is occurring',
      "Stopping deletes the previous data and restarts the cyclical test",
    ] },
  { id: "1.11.9", f: "1.11", title: "Display Graph", shot: "cyclical_test", hl: "graph",
    us: "As a test fixture user, I want to look at a live graph of the Cyclical test while it is running.",
    ac: [
      "The right side of the page displays a live Force vs Time graph while a cyclical test is running",
      "The graph is blank when nothing is running",
      "Completing the cyclical test saves the graph to the previously selected save folder",
    ] },
  { id: "1.11.11", f: "1.11", title: "Info Icons", shot: "cyclical_test",
    us: "As a test fixture user, I want informational help icons throughout the window so that I can quickly understand fields, workflows, and testing terminology without needing external documentation.",
    ac: [
      "Help icons appear beside important labels and controls",
      "Hovering displays a concise info tooltip that disappears on mouse-out",
      "Tooltips do not block surrounding UI interaction unnecessarily",
    ] },
];

module.exports = { FEATURES, STORIES: S };
